apiVersion: v1
kind: Service
metadata:
  name: deallproject
spec:
  selector:
    app: deallproject
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deallproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deallproject
  template:
    metadata:
      labels:
        app: deallproject
    spec:
      containers:
        - name: deallproject
          image: hnifrma/deallproject:1.5.0
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: mongodb://mongo1:27017/deallproject?serverSelectionTimeoutMS=2000
          imagePullPolicy: Always